version: '3.9'

services:
  relay:
    image: dstanesc2/tinylicious:0.7.3
    ports:
      - "7070:7070"
    labels:
      - "relay"
    volumes:
      - data:/var/tmp
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7070" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  gui:
    image: dstanesc2/xeyes:0.0.1
    depends_on:
      - relay
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
  data:
    driver: local
